ConditionalAssignment:
  Enabled: false
StringLiterals:
  Enabled: false
RedundantReturn:
  Enabled: false
Documentation:
  Enabled: false
WordArray:
  Enabled: false
AbcSize:
  Enabled: false
MutableConstant:
  Enabled: false
SignalException:
  Enabled: false
Casecmp:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
MethodMissing:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
